import {
  Competition,
  User,
  Achievement,
  UserSkill,
  PortfolioItem,
  CommunityPost,
  ChatConversation,
  ChatMessage,
  Team,
  TeamInvitation,
  CompetitionManagement,
} from "@/types";

export const mockCompetitions: Competition[] = [
  {
    id: "1",
    title: "Vietnam Startup Challenge 2024",
    description:
      "Cuộc thi khởi nghiệp lớn nhất Việt Nam dành cho sinh viên và doanh nhân trẻ. Tìm kiếm những ý tưởng sáng tạo có thể thay đổi tương lai.",
    category: "startup",
    organizer: "Vietnam Startup Foundation",
    startDate: new Date("2025-11-15"),
    endDate: new Date("2025-12-20"),
    registrationDeadline: new Date("2025-10-31"),
    location: "TP. Hồ Chí Minh",
    isOnline: false,
    prizePool: "500.000.000 VNĐ",
    participants: 1250,
    maxParticipants: 2000,
    requiredSkills: [
      { name: "Business Planning", category: "business" },
      { name: "Presentation", category: "communication" },
      { name: "Innovation", category: "business" },
    ],
    level: "intermediate",
    tags: ["startup", "innovation", "business-plan", "investment"],
    imageUrl: "/api/placeholder/600/400",
    website: "https://vietnamstartup.vn",
    featured: true,
    status: "registration-open",
    isRegistered: true,
    isInterested: true,
    registrationDate: new Date("2025-10-15"),
  },
  {
    id: "2",
    title: "ACM ICPC Vietnam Regional 2024",
    description:
      "Cuộc thi lập trình uy tín nhất thế giới cho sinh viên. Thử thách khả năng giải quyết vấn đề và thuật toán của bạn.",
    category: "programming",
    organizer: "ACM Vietnam",
    startDate: new Date("2025-11-10"),
    endDate: new Date("2025-11-12"),
    registrationDeadline: new Date("2025-10-31"),
    location: "Hà Nội",
    isOnline: false,
    participants: 890,
    maxParticipants: 1000,
    requiredSkills: [
      { name: "Algorithms", category: "technical" },
      { name: "Data Structures", category: "technical" },
      { name: "Problem Solving", category: "technical" },
    ],
    level: "advanced",
    tags: ["programming", "algorithms", "competitive-programming"],
    imageUrl: "/api/placeholder/600/400",
    website: "https://icpc.baylor.edu",
    featured: true,
    status: "registration-open",
    isRegistered: true,
    isInterested: false,
    registrationDate: new Date("2025-10-20"),
  },
  {
    id: "3",
    title: "Design Thinking Workshop & Competition",
    description:
      "Cuộc thi thiết kế UX/UI kết hợp với workshop từ các chuyên gia hàng đầu. Tạo ra những sản phẩm số có tác động xã hội.",
    category: "design",
    organizer: "Vietnam Design Council",
    startDate: new Date("2025-11-20"),
    endDate: new Date("2025-11-22"),
    registrationDeadline: new Date("2025-10-31"),
    location: "Đà Nẵng",
    isOnline: true,
    prizePool: "100.000.000 VNĐ",
    participants: 450,
    maxParticipants: 500,
    requiredSkills: [
      { name: "UI/UX Design", category: "design" },
      { name: "Design Thinking", category: "design" },
      { name: "Prototyping", category: "design" },
    ],
    level: "intermediate",
    tags: ["design", "ux", "ui", "social-impact"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
    isRegistered: false,
    isInterested: true,
  },
  {
    id: "4",
    title: "National Science Fair 2024",
    description:
      "Triển lãm khoa học quốc gia cho học sinh, sinh viên trình bày các dự án nghiên cứu khoa học và công nghệ.",
    category: "science",
    organizer: "Ministry of Education",
    startDate: new Date("2025-12-15"),
    endDate: new Date("2025-12-17"),
    registrationDeadline: new Date("2025-11-30"),
    location: "Hà Nội",
    isOnline: false,
    participants: 680,
    requiredSkills: [
      { name: "Research", category: "science" },
      { name: "Scientific Writing", category: "communication" },
      { name: "Data Analysis", category: "technical" },
    ],
    level: "intermediate",
    tags: ["science", "research", "technology", "innovation"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
  },
  {
    id: "5",
    title: "Vietnam Mathematics Olympiad",
    description:
      "Kỳ thi Olympic Toán học Việt Nam dành cho học sinh trung học phổ thông, tuyển chọn đội tuyển quốc gia.",
    category: "mathematics",
    organizer: "Vietnam Mathematical Society",
    startDate: new Date("2025-12-05"),
    endDate: new Date("2025-12-07"),
    registrationDeadline: new Date("2025-11-30"),
    location: "Nationwide",
    isOnline: false,
    participants: 2000,
    requiredSkills: [
      { name: "Advanced Mathematics", category: "science" },
      { name: "Problem Solving", category: "technical" },
      { name: "Logic", category: "technical" },
    ],
    level: "expert",
    tags: ["mathematics", "olympiad", "competition"],
    imageUrl: "/api/placeholder/600/400",
    featured: true,
    status: "registration-open",
    isRegistered: false,
    isInterested: true,
  },
  {
    id: "6",
    title: "Web Development Hackathon 2024",
    description:
      "Cuộc thi lập trình web 48 giờ liên tục. Tạo ra những ứng dụng web sáng tạo và hữu ích cho cộng đồng.",
    category: "programming",
    organizer: "Vietnam Web Developers Community",
    startDate: new Date("2025-12-25"),
    endDate: new Date("2025-12-27"),
    registrationDeadline: new Date("2025-12-20"),
    location: "TP. Hồ Chí Minh",
    isOnline: true,
    prizePool: "200.000.000 VNĐ",
    participants: 120,
    maxParticipants: 300,
    requiredSkills: [
      { name: "Web Development", category: "technical" },
      { name: "JavaScript", category: "technical" },
      { name: "React", category: "technical" },
    ],
    level: "intermediate",
    tags: ["web-development", "hackathon", "javascript", "react"],
    imageUrl: "/api/placeholder/600/400",
    featured: true,
    status: "registration-open",
    isRegistered: true,
    isInterested: true,
    registrationDate: new Date("2025-12-10"),
  },
  {
    id: "7",
    title: "Mobile App Development Challenge",
    description:
      "Cuộc thi phát triển ứng dụng di động cho iOS và Android. Tạo ra những app có tác động tích cực đến xã hội.",
    category: "programming",
    organizer: "Vietnam Mobile Developers Association",
    startDate: new Date("2025-01-15"),
    endDate: new Date("2025-01-17"),
    registrationDeadline: new Date("2025-01-10"),
    location: "Hà Nội",
    isOnline: false,
    prizePool: "150.000.000 VNĐ",
    participants: 85,
    maxParticipants: 200,
    requiredSkills: [
      { name: "Mobile Development", category: "technical" },
      { name: "React Native", category: "technical" },
      { name: "UI/UX Design", category: "design" },
    ],
    level: "intermediate",
    tags: ["mobile", "app-development", "react-native", "social-impact"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
  },
  {
    id: "8",
    title: "Digital Marketing Competition",
    description:
      "Cuộc thi marketing số cho các thương hiệu thực tế. Thể hiện khả năng sáng tạo và chiến lược marketing.",
    category: "business",
    organizer: "Vietnam Digital Marketing Association",
    startDate: new Date("2025-01-25"),
    endDate: new Date("2025-01-27"),
    registrationDeadline: new Date("2025-01-20"),
    location: "TP. Hồ Chí Minh",
    isOnline: true,
    prizePool: "100.000.000 VNĐ",
    participants: 320,
    maxParticipants: 500,
    requiredSkills: [
      { name: "Digital Marketing", category: "business" },
      { name: "Social Media", category: "business" },
      { name: "Content Creation", category: "communication" },
    ],
    level: "beginner",
    tags: ["marketing", "digital", "social-media", "content"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
  },
  {
    id: "9",
    title: "AI/ML Innovation Challenge",
    description:
      "Cuộc thi sáng tạo AI/ML cho các vấn đề thực tế. Phát triển các giải pháp AI có thể ứng dụng trong cuộc sống.",
    category: "programming",
    organizer: "Vietnam AI Research Institute",
    startDate: new Date("2025-02-05"),
    endDate: new Date("2025-02-07"),
    registrationDeadline: new Date("2025-01-30"),
    location: "Đà Nẵng",
    isOnline: false,
    prizePool: "300.000.000 VNĐ",
    participants: 156,
    maxParticipants: 300,
    requiredSkills: [
      { name: "Machine Learning", category: "technical" },
      { name: "Python", category: "technical" },
      { name: "Data Science", category: "technical" },
    ],
    level: "advanced",
    tags: ["ai", "machine-learning", "python", "innovation"],
    imageUrl: "/api/placeholder/600/400",
    featured: true,
    status: "registration-open",
  },
  {
    id: "10",
    title: "Graphic Design Contest",
    description:
      "Cuộc thi thiết kế đồ họa cho các dự án thương hiệu. Tạo ra những thiết kế sáng tạo và chuyên nghiệp.",
    category: "design",
    organizer: "Vietnam Designers Network",
    startDate: new Date("2025-02-15"),
    endDate: new Date("2025-02-17"),
    registrationDeadline: new Date("2025-02-10"),
    location: "Huế",
    isOnline: true,
    prizePool: "80.000.000 VNĐ",
    participants: 245,
    maxParticipants: 400,
    requiredSkills: [
      { name: "Graphic Design", category: "design" },
      { name: "Adobe Creative Suite", category: "design" },
      { name: "Brand Identity", category: "design" },
    ],
    level: "intermediate",
    tags: ["graphic-design", "branding", "adobe", "creativity"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
  },
  {
    id: "11",
    title: "Data Science Hackathon",
    description:
      "Cuộc thi phân tích dữ liệu và khoa học dữ liệu. Khám phá insights từ big data và tạo ra các mô hình dự đoán.",
    category: "programming",
    organizer: "Vietnam Data Science Community",
    startDate: new Date("2025-02-25"),
    endDate: new Date("2025-02-27"),
    registrationDeadline: new Date("2025-02-20"),
    location: "TP. Hồ Chí Minh",
    isOnline: false,
    prizePool: "250.000.000 VNĐ",
    participants: 189,
    maxParticipants: 300,
    requiredSkills: [
      { name: "Data Analysis", category: "technical" },
      { name: "Python", category: "technical" },
      { name: "Statistics", category: "science" },
    ],
    level: "advanced",
    tags: ["data-science", "analytics", "python", "statistics"],
    imageUrl: "/api/placeholder/600/400",
    featured: true,
    status: "registration-open",
  },
  {
    id: "12",
    title: "Business Plan Competition",
    description:
      "Cuộc thi lập kế hoạch kinh doanh cho các ý tưởng startup. Trình bày mô hình kinh doanh khả thi và bền vững.",
    category: "business",
    organizer: "Vietnam Business Incubator",
    startDate: new Date("2025-03-05"),
    endDate: new Date("2025-03-07"),
    registrationDeadline: new Date("2025-02-28"),
    location: "Hà Nội",
    isOnline: true,
    prizePool: "400.000.000 VNĐ",
    participants: 178,
    maxParticipants: 300,
    requiredSkills: [
      { name: "Business Planning", category: "business" },
      { name: "Financial Modeling", category: "business" },
      { name: "Market Research", category: "business" },
    ],
    level: "intermediate",
    tags: ["business-plan", "startup", "financial-modeling", "market-research"],
    imageUrl: "/api/placeholder/600/400",
    featured: true,
    status: "registration-open",
  },
  {
    id: "13",
    title: "UI/UX Design Sprint",
    description:
      "Cuộc thi thiết kế trải nghiệm người dùng trong 5 ngày. Tạo ra prototype hoàn chỉnh cho các vấn đề thực tế.",
    category: "design",
    organizer: "Vietnam UX Designers Association",
    startDate: new Date("2025-03-15"),
    endDate: new Date("2025-03-19"),
    registrationDeadline: new Date("2025-03-10"),
    location: "TP. Hồ Chí Minh",
    isOnline: false,
    prizePool: "120.000.000 VNĐ",
    participants: 95,
    maxParticipants: 150,
    requiredSkills: [
      { name: "UI/UX Design", category: "design" },
      { name: "Prototyping", category: "design" },
      { name: "User Research", category: "design" },
    ],
    level: "intermediate",
    tags: ["ux", "ui", "prototyping", "user-research"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
  },
  {
    id: "14",
    title: "Cybersecurity Challenge",
    description:
      "Cuộc thi bảo mật thông tin và an ninh mạng. Thử thách khả năng phát hiện và khắc phục lỗ hổng bảo mật.",
    category: "programming",
    organizer: "Vietnam Cybersecurity Association",
    startDate: new Date("2025-03-25"),
    endDate: new Date("2025-03-27"),
    registrationDeadline: new Date("2025-03-20"),
    location: "Đà Nẵng",
    isOnline: true,
    prizePool: "180.000.000 VNĐ",
    participants: 134,
    maxParticipants: 200,
    requiredSkills: [
      { name: "Cybersecurity", category: "technical" },
      { name: "Network Security", category: "technical" },
      { name: "Penetration Testing", category: "technical" },
    ],
    level: "advanced",
    tags: ["cybersecurity", "network-security", "penetration-testing"],
    imageUrl: "/api/placeholder/600/400",
    featured: false,
    status: "registration-open",
  },
  {
    id: "15",
    title: "Environmental Innovation Contest",
    description:
      "Cuộc thi sáng tạo giải pháp bảo vệ môi trường. Phát triển các công nghệ xanh và bền vững.",
    category: "science",
    organizer: "Vietnam Environmental Protection Agency",
    startDate: new Date("2025-04-05"),
    endDate: new Date("2025-04-07"),
    registrationDeadline: new Date("2025-03-30"),
    location: "Cần Thơ",
    isOnline: false,
    prizePool: "200.000.000 VNĐ",
    participants: 89,
    maxParticipants: 150,
    requiredSkills: [
      { name: "Environmental Science", category: "science" },
      { name: "Innovation", category: "business" },
      { name: "Sustainability", category: "science" },
    ],
    level: "intermediate",
    tags: ["environment", "innovation", "sustainability", "green-tech"],
    imageUrl: "/api/placeholder/600/400",
    featured: true,
    status: "registration-open",
  },
];

export const mockUsers: User[] = [
  {
    id: "1",
    username: "nguyenvana",
    fullName: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    avatar: "/api/placeholder/150/150",
    bio: "Sinh viên Khoa học Máy tính tại ĐH Bách Khoa. Đam mê lập trình và AI.",
    school: "Đại học Bách Khoa Hà Nội",
    location: {
      city: "Hà Nội",
      region: "Miền Bắc",
      country: "Vietnam",
    },
    skills: [
      {
        name: "Python",
        category: "technical",
        level: "advanced",
        experienceYears: 3,
        certifications: [
          {
            name: "Python Programming Certification",
            issuer: "Coursera",
            date: new Date("2023-06-15"),
            url: "https://coursera.org/verify/certificate",
          },
        ],
      },
      {
        name: "Machine Learning",
        category: "technical",
        level: "intermediate",
        experienceYears: 2,
      },
      {
        name: "Web Development",
        category: "technical",
        level: "advanced",
        experienceYears: 4,
      },
    ],
    interests: ["AI", "Web Development", "Competitive Programming"],
    studyField: "Computer Science",
    achievements: [
      {
        id: "1",
        competitionId: "2",
        competitionTitle: "ACM ICPC Vietnam Regional 2023",
        position: 15,
        award: "Bronze Medal",
        date: new Date("2023-04-10"),
        category: "programming",
      },
    ],
    portfolio: [
      {
        id: "1",
        title: "AI Chatbot for Customer Service",
        description: "Phát triển chatbot AI sử dụng NLP để hỗ trợ khách hàng",
        category: "AI/ML",
        tags: ["Python", "NLP", "Chatbot"],
        githubUrl: "https://github.com/user/ai-chatbot",
        date: new Date("2023-12-01"),
        featured: true,
      },
    ],
    socialLinks: {
      github: "https://github.com/nguyenvana",
      linkedin: "https://linkedin.com/in/nguyenvana",
    },
    joinDate: new Date("2023-01-15"),
    isVerified: true,
    rating: 4.8,
    collaborationHistory: [
      {
        id: "1",
        partnerId: "2",
        partnerName: "Trần Thị B",
        competitionId: "2",
        competitionTitle: "ACM ICPC Vietnam Regional 2023",
        date: new Date("2023-04-10"),
        rating: 5,
        comment: "Làm việc rất hiệu quả, kỹ năng lập trình xuất sắc",
        skills: ["Python", "Algorithms", "Problem Solving"],
      },
    ],
  },
  {
    id: "2",
    username: "tranthib",
    fullName: "Trần Thị B",
    email: "tranthib@example.com",
    avatar: "/api/placeholder/150/150",
    bio: "UX/UI Designer với 3 năm kinh nghiệm. Chuyên thiết kế sản phẩm số.",
    school: "Đại học Kiến trúc Hà Nội",
    location: {
      city: "TP. Hồ Chí Minh",
      region: "Miền Nam",
      country: "Vietnam",
    },
    skills: [
      {
        name: "UI/UX Design",
        category: "design",
        level: "expert",
        experienceYears: 3,
        certifications: [
          {
            name: "Google UX Design Certificate",
            issuer: "Google",
            date: new Date("2023-08-20"),
            url: "https://coursera.org/verify/google-ux",
          },
          {
            name: "Figma Design Master",
            issuer: "Figma",
            date: new Date("2023-11-10"),
            url: "https://figma.com/certificate",
          },
        ],
      },
      {
        name: "Figma",
        category: "design",
        level: "expert",
        experienceYears: 3,
      },
      {
        name: "Design Thinking",
        category: "design",
        level: "advanced",
        experienceYears: 2,
      },
    ],
    interests: ["UX Research", "Product Design", "Design Systems"],
    studyField: "Design",
    achievements: [
      {
        id: "2",
        competitionId: "3",
        competitionTitle: "Design Thinking Workshop 2023",
        position: 1,
        award: "First Prize",
        date: new Date("2023-03-22"),
        category: "design",
      },
    ],
    portfolio: [
      {
        id: "2",
        title: "E-commerce Mobile App",
        description: "Thiết kế UX/UI cho ứng dụng thương mại điện tử",
        category: "Mobile Design",
        tags: ["Mobile", "E-commerce", "UX"],
        projectUrl: "https://behance.net/project",
        date: new Date("2023-11-15"),
        featured: true,
      },
    ],
    socialLinks: {
      behance: "https://behance.net/tranthib",
      linkedin: "https://linkedin.com/in/tranthib",
    },
    joinDate: new Date("2023-02-20"),
    isVerified: true,
    rating: 4.9,
    collaborationHistory: [
      {
        id: "2",
        partnerId: "1",
        partnerName: "Nguyễn Văn A",
        competitionId: "2",
        competitionTitle: "ACM ICPC Vietnam Regional 2023",
        date: new Date("2023-04-10"),
        rating: 5,
        comment: "Thiết kế UI/UX rất đẹp và chuyên nghiệp",
        skills: ["UI/UX Design", "Figma", "Design Thinking"],
      },
      {
        id: "3",
        partnerId: "4",
        partnerName: "Hoàng Văn D",
        competitionId: "3",
        competitionTitle: "Design Thinking Workshop 2023",
        date: new Date("2023-03-22"),
        rating: 4,
        comment: "Có ý tưởng sáng tạo tốt, teamwork hiệu quả",
        skills: ["Design Thinking", "UX Research", "Prototyping"],
      },
    ],
  },
  {
    id: "3",
    username: "levanc",
    fullName: "Lê Văn C",
    email: "levanc@example.com",
    avatar: "/api/placeholder/150/150",
    bio: "Sinh viên năm 4 ngành Kỹ thuật Phần mềm. Có kinh nghiệm 2 năm competitive programming, rating Codeforces 1800+.",
    school: "Đại học Công nghệ",
    location: {
      city: "Hà Nội",
      region: "Miền Bắc",
      country: "Vietnam",
    },
    skills: [
      {
        name: "C++",
        category: "technical",
        level: "advanced",
        experienceYears: 3,
      },
      {
        name: "Algorithms",
        category: "technical",
        level: "advanced",
        experienceYears: 2,
      },
      {
        name: "Data Structures",
        category: "technical",
        level: "intermediate",
        experienceYears: 2,
      },
    ],
    interests: ["Competitive Programming", "Algorithms", "Problem Solving"],
    studyField: "Software Engineering",
    achievements: [
      {
        id: "3",
        competitionId: "2",
        competitionTitle: "ACM ICPC Vietnam Regional 2023",
        position: 25,
        award: "Participation Certificate",
        date: new Date("2023-04-10"),
        category: "programming",
      },
    ],
    portfolio: [],
    socialLinks: {
      github: "https://github.com/levanc",
    },
    joinDate: new Date("2023-03-10"),
    isVerified: false,
    rating: 4.2,
    collaborationHistory: [
      {
        id: "4",
        partnerId: "1",
        partnerName: "Nguyễn Văn A",
        competitionId: "2",
        competitionTitle: "ACM ICPC Vietnam Regional 2023",
        date: new Date("2023-04-10"),
        rating: 4,
        comment: "Kỹ năng giải thuật tốt, cần cải thiện teamwork",
        skills: ["C++", "Algorithms", "Data Structures"],
      },
    ],
  },
  {
    id: "4",
    username: "hoangvand",
    fullName: "Hoàng Văn D",
    email: "hoangvand@example.com",
    avatar: "/api/placeholder/150/150",
    bio: "Co-founder của startup FinTech. Có kinh nghiệm 4 năm trong lĩnh vực business development và product management.",
    school: "Đại học Kinh tế Quốc dân",
    location: {
      city: "TP. Hồ Chí Minh",
      region: "Miền Nam",
      country: "Vietnam",
    },
    skills: [
      {
        name: "Business Development",
        category: "business",
        level: "expert",
        experienceYears: 4,
      },
      {
        name: "Product Management",
        category: "business",
        level: "advanced",
        experienceYears: 3,
      },
      {
        name: "Market Research",
        category: "business",
        level: "advanced",
        experienceYears: 3,
      },
    ],
    interests: ["Startup", "FinTech", "Business Strategy", "Innovation"],
    studyField: "Business Administration",
    achievements: [
      {
        id: "4",
        competitionId: "1",
        competitionTitle: "Vietnam Startup Challenge 2023",
        position: 5,
        award: "Top 5 Finalist",
        date: new Date("2023-05-20"),
        category: "startup",
      },
    ],
    portfolio: [
      {
        id: "3",
        title: "FinTech Payment Platform",
        description:
          "Nền tảng thanh toán cho sinh viên với tính năng quản lý chi tiêu thông minh",
        category: "Business",
        tags: ["FinTech", "Payment", "Mobile App"],
        projectUrl: "https://fintech-demo.com",
        date: new Date("2023-10-01"),
        featured: true,
      },
    ],
    socialLinks: {
      linkedin: "https://linkedin.com/in/hoangvand",
    },
    joinDate: new Date("2023-01-05"),
    isVerified: true,
    rating: 4.7,
    collaborationHistory: [
      {
        id: "5",
        partnerId: "2",
        partnerName: "Trần Thị B",
        competitionId: "3",
        competitionTitle: "Design Thinking Workshop 2023",
        date: new Date("2023-03-22"),
        rating: 5,
        comment: "Lãnh đạo nhóm xuất sắc, có tầm nhìn chiến lược rõ ràng",
        skills: ["Business Development", "Product Management", "Leadership"],
      },
    ],
  },
  {
    id: "5",
    username: "nguyenthie",
    fullName: "Nguyễn Thị E",
    email: "nguyenthie@example.com",
    avatar: "/api/placeholder/150/150",
    bio: "Nghiên cứu sinh ngành Khoa học Dữ liệu. Đam mê Machine Learning và Data Analysis, có nhiều project về AI application.",
    school: "Đại học Khoa học Tự nhiên",
    location: {
      city: "Hà Nội",
      region: "Miền Bắc",
      country: "Vietnam",
    },
    skills: [
      {
        name: "Python",
        category: "technical",
        level: "expert",
        experienceYears: 4,
      },
      {
        name: "Machine Learning",
        category: "technical",
        level: "expert",
        experienceYears: 3,
      },
      {
        name: "Data Analysis",
        category: "technical",
        level: "advanced",
        experienceYears: 3,
      },
      {
        name: "Research",
        category: "science",
        level: "advanced",
        experienceYears: 2,
      },
    ],
    interests: ["Machine Learning", "Data Science", "Research", "AI Ethics"],
    studyField: "Data Science",
    achievements: [
      {
        id: "5",
        competitionId: "4",
        competitionTitle: "National Science Fair 2023",
        position: 2,
        award: "Silver Medal",
        date: new Date("2023-05-17"),
        category: "science",
      },
    ],
    portfolio: [
      {
        id: "4",
        title: "COVID-19 Prediction Model",
        description:
          "Mô hình ML dự đoán xu hướng COVID-19 dựa trên dữ liệu y tế và xã hội",
        category: "Machine Learning",
        tags: ["Python", "TensorFlow", "Healthcare"],
        githubUrl: "https://github.com/user/covid-prediction",
        date: new Date("2023-08-15"),
        featured: true,
      },
    ],
    socialLinks: {
      github: "https://github.com/nguyenthie",
      linkedin: "https://linkedin.com/in/nguyenthie",
    },
    joinDate: new Date("2022-12-20"),
    isVerified: true,
    rating: 4.9,
    collaborationHistory: [],
  },
  {
    id: "6",
    username: "phamvanf",
    fullName: "Phạm Văn F",
    email: "phamvanf@example.com",
    avatar: "/api/placeholder/150/150",
    bio: "Full-stack developer với 3 năm kinh nghiệm. Chuyên về React, Node.js và cloud deployment. Thích làm việc nhóm và học hỏi công nghệ mới.",
    school: "Đại học FPT",
    location: {
      city: "Đà Nẵng",
      region: "Miền Trung",
      country: "Vietnam",
    },
    skills: [
      {
        name: "React",
        category: "technical",
        level: "advanced",
        experienceYears: 3,
      },
      {
        name: "Node.js",
        category: "technical",
        level: "advanced",
        experienceYears: 3,
      },
      {
        name: "TypeScript",
        category: "technical",
        level: "intermediate",
        experienceYears: 2,
      },
      {
        name: "Cloud Computing",
        category: "technical",
        level: "intermediate",
        experienceYears: 1,
      },
    ],
    interests: ["Web Development", "Cloud Technology", "DevOps", "Open Source"],
    studyField: "Computer Science",
    achievements: [],
    portfolio: [
      {
        id: "5",
        title: "E-learning Platform",
        description:
          "Nền tảng học trực tuyến với tính năng video call và quản lý bài tập",
        category: "Web Development",
        tags: ["React", "Node.js", "Socket.io"],
        githubUrl: "https://github.com/user/elearning",
        projectUrl: "https://elearning-demo.com",
        date: new Date("2023-09-01"),
        featured: true,
      },
    ],
    socialLinks: {
      github: "https://github.com/phamvanf",
    },
    joinDate: new Date("2023-02-14"),
    isVerified: false,
    rating: 4.3,
    collaborationHistory: [],
  },
];

export const skillCategories = [
  { name: "Programming", color: "skill-coding" },
  { name: "Design", color: "skill-design" },
  { name: "Business", color: "skill-business" },
  { name: "Science", color: "skill-science" },
  { name: "Communication", color: "blue-500" },
  { name: "Leadership", color: "purple-500" },
];

export const competitionCategories = [
  { name: "programming", label: "Lập trình", icon: "💻" },
  { name: "design", label: "Thiết kế", icon: "🎨" },
  { name: "business", label: "Kinh doanh", icon: "💼" },
  { name: "science", label: "Khoa học", icon: "🔬" },
  { name: "mathematics", label: "Toán học", icon: "📐" },
  { name: "innovation", label: "Sáng tạo", icon: "💡" },
  { name: "startup", label: "Khởi nghiệp", icon: "🚀" },
  { name: "creative", label: "Sáng tạo", icon: "✨" },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: "1",
    authorId: "1",
    author: {
      id: "1",
      fullName: "Nguyễn Văn A",
      username: "nguyenvana",
      avatar: "/api/placeholder/150/150",
      school: "Đại học Bách Khoa Hà Nội",
      isVerified: true,
    },
    title: "Tìm teammate lập trình cho ACM ICPC 2024",
    content:
      "Mình đang tìm 2 bạn có kinh nghiệm về algorithms và data structures để tham gia ACM ICPC Vietnam Regional 2024. Team mình hiện tại thiếu 2 người, mình có 3 năm kinh nghiệm competitive programming và đã từng đạt top 20 năm ngoái.",
    competitionId: "2",
    competitionTitle: "ACM ICPC Vietnam Regional 2024",
    requiredSkills: ["C++", "Algorithms", "Data Structures", "Problem Solving"],
    teamSize: 3,
    currentMembers: 1,
    location: "Hà Nội",
    isRemote: false,
    deadline: new Date("2024-03-01"),
    tags: ["programming", "algorithms", "teamwork", "icpc"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    likes: 15,
    comments: [
      {
        id: "1",
        authorId: "2",
        author: {
          id: "2",
          fullName: "Trần Thị B",
          username: "tranthib",
          avatar: "/api/placeholder/150/150",
        },
        content:
          "Mình có interest, bạn có thể share thêm về kinh nghiệm của team không?",
        createdAt: new Date("2024-01-16"),
        likes: 3,
      },
    ],
    applicants: [
      {
        id: "1",
        userId: "3",
        user: {
          id: "3",
          fullName: "Lê Văn C",
          username: "levanc",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Công nghệ",
          skills: ["C++", "Python", "Algorithms"],
        },
        message:
          "Chào bạn! Mình có 2 năm kinh nghiệm competitive programming, từng tham gia nhiều contest trên Codeforces. Rating hiện tại là 1800+. Rất muốn join team!",
        appliedAt: new Date("2024-01-16"),
        status: "pending",
      },
    ],
    status: "open",
    type: "find-members",
  },
  {
    id: "2",
    authorId: "2",
    author: {
      id: "2",
      fullName: "Trần Thị B",
      username: "tranthib",
      avatar: "/api/placeholder/150/150",
      school: "Đại học Kiến trúc Hà Nội",
      isVerified: true,
    },
    title: "Designer tìm team cho Design Thinking Competition",
    content:
      "Mình là UX/UI Designer với 3 năm kinh nghiệm, đang tìm team gồm 1 developer và 1 business analyst để tham gia cuộc thi Design Thinking. Mình có kinh nghiệm làm việc với startup và đã thắng nhiều cuộc thi design.",
    competitionId: "3",
    competitionTitle: "Design Thinking Workshop & Competition",
    requiredSkills: [
      "Business Analysis",
      "Frontend Development",
      "Product Management",
    ],
    teamSize: 3,
    currentMembers: 1,
    isRemote: true,
    deadline: new Date("2024-03-05"),
    tags: ["design", "business", "frontend", "remote"],
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    likes: 8,
    comments: [],
    applicants: [],
    status: "open",
    type: "find-members",
  },
  {
    id: "3",
    authorId: "4",
    author: {
      id: "4",
      fullName: "Hoàng Văn D",
      username: "hoangvand",
      avatar: "/api/placeholder/150/150",
      school: "Đại học Kinh tế Quốc dân",
      isVerified: false,
    },
    title: "Startup team cần thêm CTO cho Vietnam Startup Challenge",
    content:
      "Chúng mình có ý tưởng về FinTech platform cho sinh viên, đã có business plan hoàn chỉnh và prototype. Hiện tại team có CEO, CMO và cần thêm 1 CTO có kinh nghiệm về backend và mobile development để cùng tham gia cuộc thi.",
    competitionId: "1",
    competitionTitle: "Vietnam Startup Challenge 2024",
    requiredSkills: [
      "Backend Development",
      "Mobile Development",
      "System Architecture",
      "Leadership",
    ],
    teamSize: 4,
    currentMembers: 3,
    location: "TP. Hồ Chí Minh",
    isRemote: false,
    deadline: new Date("2024-02-20"),
    tags: ["startup", "fintech", "cto", "backend"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    likes: 25,
    comments: [
      {
        id: "2",
        authorId: "1",
        author: {
          id: "1",
          fullName: "Nguyễn Văn A",
          username: "nguyenvana",
          avatar: "/api/placeholder/150/150",
        },
        content:
          "Ý tưởng rất hay! Bạn có thể share thêm về tech stack dự định sử dụng không?",
        createdAt: new Date("2024-01-21"),
        likes: 2,
      },
    ],
    applicants: [],
    status: "open",
    type: "find-members",
  },
];

export const mockChatConversations: ChatConversation[] = [
  {
    id: "1",
    participants: ["1", "2"],
    participantDetails: [
      {
        id: "2",
        fullName: "Trần Thị B",
        username: "tranthib",
        avatar: "/api/placeholder/150/150",
        isOnline: true,
        lastSeen: new Date(),
      },
    ],
    lastMessage: {
      id: "3",
      conversationId: "1",
      senderId: "2",
      content:
        "Cảm ơn bạn đã share thông tin về cuộc thi! Mình sẽ cân nhắc join team.",
      messageType: "text",
      createdAt: new Date("2024-01-21T14:30:00"),
      readBy: ["2"],
    },
    lastActivity: new Date("2024-01-21T14:30:00"),
    isGroup: false,
    unreadCount: 1,
    type: "direct",
  },
  {
    id: "2",
    participants: ["1", "3", "4"],
    participantDetails: [
      {
        id: "3",
        fullName: "Lê Văn C",
        username: "levanc",
        avatar: "/api/placeholder/150/150",
        isOnline: false,
        lastSeen: new Date("2024-01-21T10:00:00"),
      },
      {
        id: "4",
        fullName: "Hoàng Văn D",
        username: "hoangvand",
        avatar: "/api/placeholder/150/150",
        isOnline: true,
        lastSeen: new Date(),
      },
    ],
    lastMessage: {
      id: "5",
      conversationId: "2",
      senderId: "4",
      content: "Chúng ta hẹn gặp vào thứ 2 tới để discuss về dự án nhé!",
      messageType: "text",
      createdAt: new Date("2024-01-20T16:45:00"),
      readBy: ["4", "1"],
    },
    lastActivity: new Date("2024-01-20T16:45:00"),
    isGroup: true,
    groupName: "ICPC Team Discussion",
    unreadCount: 0,
    type: "post-related",
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "1",
    conversationId: "1",
    senderId: "1",
    content:
      "Chào bạn! Mình thấy bạn comment trong post tìm teammate. Bạn có muốn chat để trao đổi thêm không?",
    messageType: "text",
    createdAt: new Date("2024-01-21T14:15:00"),
    readBy: ["1", "2"],
  },
  {
    id: "2",
    conversationId: "1",
    senderId: "2",
    content:
      "Chào bạn! Mình rất có hứng thú. Bạn có thể kể thêm về kinh nghiệm và plan chuẩn bị cho cuộc thi không?",
    messageType: "text",
    createdAt: new Date("2024-01-21T14:20:00"),
    readBy: ["1", "2"],
  },
  {
    id: "3",
    conversationId: "1",
    senderId: "2",
    content:
      "Cảm ơn bạn đã share thông tin về cuộc thi! Mình sẽ cân nhắc join team.",
    messageType: "text",
    createdAt: new Date("2024-01-21T14:30:00"),
    readBy: ["2"],
  },
  {
    id: "4",
    conversationId: "2",
    senderId: "1",
    content:
      "Chào team! Chúng ta đã có đủ thành viên rồi. Ai có ý kiến gì về lịch training không?",
    messageType: "text",
    createdAt: new Date("2024-01-20T16:30:00"),
    readBy: ["1", "3", "4"],
  },
  {
    id: "5",
    conversationId: "2",
    senderId: "4",
    content: "Chúng ta hẹn gặp vào thứ 2 tới để discuss về dự án nhé!",
    messageType: "text",
    createdAt: new Date("2024-01-20T16:45:00"),
    readBy: ["4", "1"],
  },
];

export const mockTeams: Team[] = [
  {
    id: "1",
    name: "CodeMasters",
    description:
      "Đội thi lập trình chuyên nghiệp, tập trung vào ACM ICPC và các cuộc thi algorithms. Chúng tôi có kinh nghiệm 2+ năm thi đấu cùng nhau.",
    avatar: "/api/placeholder/150/150",
    leaderId: "1",
    leader: {
      id: "1",
      userId: "1",
      user: {
        id: "1",
        fullName: "Nguyễn Văn A",
        username: "nguyenvana",
        avatar: "/api/placeholder/150/150",
        school: "Đại học Bách Khoa Hà Nội",
        skills: ["Python", "C++", "Algorithms"],
      },
      role: "leader",
      joinedAt: new Date("2023-09-01"),
      contribution: "Team Leader & Algorithm Expert",
      status: "active",
    },
    members: [
      {
        id: "1",
        userId: "1",
        user: {
          id: "1",
          fullName: "Nguyễn Văn A",
          username: "nguyenvana",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Bách Khoa Hà Nội",
          skills: ["Python", "C++", "Algorithms"],
        },
        role: "leader",
        joinedAt: new Date("2023-09-01"),
        contribution: "Team Leader & Algorithm Expert",
        status: "active",
      },
      {
        id: "2",
        userId: "3",
        user: {
          id: "3",
          fullName: "Lê Văn C",
          username: "levanc",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Công nghệ",
          skills: ["C++", "Algorithms", "Data Structures"],
        },
        role: "member",
        joinedAt: new Date("2023-09-15"),
        contribution: "Data Structures Specialist",
        status: "active",
      },
      {
        id: "3",
        userId: "6",
        user: {
          id: "6",
          fullName: "Phạm Văn F",
          username: "phamvanf",
          avatar: "/api/placeholder/150/150",
          school: "Đại học FPT",
          skills: ["React", "Node.js", "TypeScript"],
        },
        role: "member",
        joinedAt: new Date("2023-10-01"),
        contribution: "Implementation & Testing",
        status: "active",
      },
    ],
    competitionId: "2",
    competitionTitle: "ACM ICPC Vietnam Regional 2024",
    skills: ["C++", "Algorithms", "Data Structures", "Problem Solving"],
    goals: [
      "Đạt top 10 trong ACM ICPC Vietnam",
      "Improve teamwork skills",
      "Practice 5h/week",
    ],
    isPrivate: false,
    maxMembers: 3,
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-01-20"),
    status: "active",
    inviteCode: "CM2024",
    location: "Hà Nội",
    isRemote: false,
  },
  {
    id: "2",
    name: "Design Innovators",
    description:
      "Nhóm designer trẻ đam mê UX/UI và design thinking. Chuyên tham gia các cuộc thi thiết kế và hackathon về sản phẩm số.",
    avatar: "/api/placeholder/150/150",
    leaderId: "2",
    leader: {
      id: "4",
      userId: "2",
      user: {
        id: "2",
        fullName: "Trần Thị B",
        username: "tranthib",
        avatar: "/api/placeholder/150/150",
        school: "Đại học Kiến trúc Hà Nội",
        skills: ["UI/UX Design", "Figma", "Design Thinking"],
      },
      role: "leader",
      joinedAt: new Date("2023-08-15"),
      contribution: "Design Lead & Strategy",
      status: "active",
    },
    members: [
      {
        id: "4",
        userId: "2",
        user: {
          id: "2",
          fullName: "Trần Thị B",
          username: "tranthib",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Kiến trúc Hà Nội",
          skills: ["UI/UX Design", "Figma", "Design Thinking"],
        },
        role: "leader",
        joinedAt: new Date("2023-08-15"),
        contribution: "Design Lead & Strategy",
        status: "active",
      },
    ],
    competitionId: "3",
    competitionTitle: "Design Thinking Workshop & Competition",
    skills: ["UI/UX Design", "Design Thinking", "Prototyping", "User Research"],
    goals: [
      "Tạo sản phẩm có impact xã hội",
      "Học hỏi design thinking methods",
      "Networking with experts",
    ],
    isPrivate: false,
    maxMembers: 4,
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2024-01-18"),
    status: "recruiting",
    inviteCode: "DI2024",
    isRemote: true,
  },
  {
    id: "3",
    name: "FinTech Pioneers",
    description:
      "Startup team phát triển giải pháp FinTech cho sinh viên. Đang chuẩn bị cho Vietnam Startup Challenge với sản phẩm thanh toán thông minh.",
    avatar: "/api/placeholder/150/150",
    leaderId: "4",
    leader: {
      id: "5",
      userId: "4",
      user: {
        id: "4",
        fullName: "Hoàng Văn D",
        username: "hoangvand",
        avatar: "/api/placeholder/150/150",
        school: "Đại học Kinh tế Quốc dân",
        skills: [
          "Business Development",
          "Product Management",
          "Market Research",
        ],
      },
      role: "leader",
      joinedAt: new Date("2023-10-01"),
      contribution: "CEO & Business Strategy",
      status: "active",
    },
    members: [
      {
        id: "5",
        userId: "4",
        user: {
          id: "4",
          fullName: "Hoàng Văn D",
          username: "hoangvand",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Kinh tế Quốc dân",
          skills: [
            "Business Development",
            "Product Management",
            "Market Research",
          ],
        },
        role: "leader",
        joinedAt: new Date("2023-10-01"),
        contribution: "CEO & Business Strategy",
        status: "active",
      },
      {
        id: "6",
        userId: "6",
        user: {
          id: "6",
          fullName: "Phạm Văn F",
          username: "phamvanf",
          avatar: "/api/placeholder/150/150",
          school: "Đại học FPT",
          skills: ["React", "Node.js", "TypeScript"],
        },
        role: "co-leader",
        joinedAt: new Date("2023-10-15"),
        contribution: "CTO & Technical Lead",
        status: "active",
      },
    ],
    competitionId: "1",
    competitionTitle: "Vietnam Startup Challenge 2024",
    skills: [
      "Business Development",
      "Full-stack Development",
      "Product Design",
      "Market Analysis",
    ],
    goals: [
      "Đạt top 5 trong startup challenge",
      "Launch MVP product",
      "Raise pre-seed funding",
    ],
    isPrivate: false,
    maxMembers: 5,
    createdAt: new Date("2023-10-01"),
    updatedAt: new Date("2024-01-21"),
    status: "active",
    inviteCode: "FTP2024",
    location: "TP. Hồ Chí Minh",
    isRemote: false,
  },
  {
    id: "4",
    name: "Dream Team",
    description: "Nhóm mới của Nguyễn Văn A để đăng ký các cuộc thi.",
    avatar: "/api/placeholder/150/150",
    leaderId: "1",
    leader: {
      id: "1",
      userId: "1",
      user: {
        id: "1",
        fullName: "Nguyễn Văn A",
        username: "nguyenvana",
        avatar: "/api/placeholder/150/150",
        school: "Đại học Bách Khoa Hà Nội",
        skills: ["Python", "C++", "Algorithms"],
      },
      role: "leader",
      joinedAt: new Date("2024-01-01"),
      contribution: "Team Leader",
      status: "active",
    },
    members: [
      {
        id: "1",
        userId: "1",
        user: {
          id: "1",
          fullName: "Nguyễn Văn A",
          username: "nguyenvana",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Bách Khoa Hà Nội",
          skills: ["Python", "C++", "Algorithms"],
        },
        role: "leader",
        joinedAt: new Date("2024-01-01"),
        contribution: "Team Leader",
        status: "active",
      },
      {
        id: "2",
        userId: "2",
        user: {
          id: "2",
          fullName: "Trần Thị B",
          username: "tranthib",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Kiến trúc Hà Nội",
          skills: ["UI/UX Design", "Figma", "Design Thinking"],
        },
        role: "member",
        joinedAt: new Date("2024-01-02"),
        contribution: "UI/UX Designer",
        status: "active",
      },
      {
        id: "3",
        userId: "3",
        user: {
          id: "3",
          fullName: "Lê Văn C",
          username: "levanc",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Công nghệ",
          skills: ["C++", "Algorithms", "Data Structures"],
        },
        role: "member",
        joinedAt: new Date("2024-01-03"),
        contribution: "Backend Developer",
        status: "active",
      },
      {
        id: "4",
        userId: "4",
        user: {
          id: "4",
          fullName: "Hoàng Văn D",
          username: "hoangvand",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Kinh tế Quốc dân",
          skills: ["Business Development", "Product Management", "Market Research"],
        },
        role: "member",
        joinedAt: new Date("2024-01-04"),
        contribution: "Business Analyst",
        status: "active",
      },
      {
        id: "5",
        userId: "5",
        user: {
          id: "5",
          fullName: "Phạm Thị E",
          username: "phamthie",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Ngoại thương",
          skills: ["Marketing", "Communication", "Event Planning"],
        },
        role: "member",
        joinedAt: new Date("2024-01-05"),
        contribution: "Marketing",
        status: "active",
      }
    ],
    // Không có competitionId để có thể dùng đăng ký các cuộc thi mới
    skills: ["Python", "C++", "Algorithms"],
    goals: ["Tham gia nhiều cuộc thi mới"],
    isPrivate: false,
    maxMembers: 5,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    status: "active",
    inviteCode: "DT2024",
    location: "Hà Nội",
    isRemote: false,
  },
];

export const mockTeamInvitations: TeamInvitation[] = [
  {
    id: "1",
    teamId: "2",
    team: {
      id: "2",
      name: "Design Innovators",
      avatar: "/api/placeholder/150/150",
      leader: "Trần Thị B",
    },
    inviterId: "2",
    inviter: {
      id: "2",
      fullName: "Trần Thị B",
      username: "tranthib",
      avatar: "/api/placeholder/150/150",
    },
    inviteeId: "1",
    message:
      "Chào bạn! Team mình đang cần thêm 1 member có kinh nghiệm về frontend để support cho design process. Bạn có muốn join không?",
    createdAt: new Date("2024-01-20"),
    status: "pending",
  },
  {
    id: "2",
    teamId: "3",
    team: {
      id: "3",
      name: "FinTech Pioneers",
      avatar: "/api/placeholder/150/150",
      leader: "Hoàng Văn D",
    },
    inviterId: "4",
    inviter: {
      id: "4",
      fullName: "Hoàng Văn D",
      username: "hoangvand",
      avatar: "/api/placeholder/150/150",
    },
    inviteeId: "5",
    message:
      "Hi! Chúng mình rất ấn tượng với research background của bạn. Team đang cần AI/Data specialist cho fintech product. Interested?",
    createdAt: new Date("2024-01-19"),
    status: "pending",
  },
];

export const mockCompetitionManagement: CompetitionManagement[] = [
  {
    id: "1",
    competitionId: "1",
    competition: mockCompetitions[0],
    organizerId: "org1",
    organizer: {
      id: "org1",
      name: "Vietnam Startup Foundation",
      email: "admin@vietnamstartup.vn",
      avatar: "/api/placeholder/150/150",
    },
    status: "ongoing",
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-01-21"),
    settings: {
      allowLateRegistration: false,
      autoApproveRegistrations: true,
      maxParticipants: 2000,
      registrationFee: 100000,
      emailNotifications: true,
      publicLeaderboard: true,
      allowTeamRegistration: true,
      maxTeamSize: 5,
    },
    finances: {
      budget: 800000000,
      revenue: [
        {
          id: "r1",
          type: "revenue",
          category: "Phí đăng ký",
          description: "Phí đăng ký từ thí sinh",
          amount: 125000000,
          date: new Date("2024-01-15"),
          source: "Registration fees",
          status: "confirmed",
        },
        {
          id: "r2",
          type: "revenue",
          category: "Tài trợ",
          description: "Tài trợ từ TechCorp",
          amount: 300000000,
          date: new Date("2024-01-10"),
          source: "TechCorp Sponsorship",
          status: "confirmed",
        },
        {
          id: "r3",
          type: "revenue",
          category: "Tài trợ",
          description: "Tài trợ từ VinGroup",
          amount: 200000000,
          date: new Date("2024-01-05"),
          source: "VinGroup Sponsorship",
          status: "confirmed",
        },
      ],
      expenses: [
        {
          id: "e1",
          type: "expense",
          category: "Giải thưởng",
          description: "Tiền thưởng cho các đội chiến thắng",
          amount: 500000000,
          date: new Date("2024-01-20"),
          status: "pending",
        },
        {
          id: "e2",
          type: "expense",
          category: "Tổ chức sự kiện",
          description: "Thuê địa điểm, thiết bị",
          amount: 80000000,
          date: new Date("2024-01-12"),
          status: "confirmed",
        },
        {
          id: "e3",
          type: "expense",
          category: "Marketing",
          description: "Quảng cáo và marketing",
          amount: 25000000,
          date: new Date("2024-01-08"),
          status: "confirmed",
        },
      ],
      prizePool: 500000000,
      sponsorships: [
        {
          id: "s1",
          sponsor: "TechCorp",
          amount: 300000000,
          type: "cash",
          benefits: ["Logo placement", "Speaking slot", "Booth space"],
          status: "confirmed",
          contractDate: new Date("2024-01-10"),
        },
        {
          id: "s2",
          sponsor: "VinGroup",
          amount: 200000000,
          type: "cash",
          benefits: ["Logo placement", "Networking session"],
          status: "confirmed",
          contractDate: new Date("2024-01-05"),
        },
      ],
      totalRevenue: 625000000,
      totalExpenses: 605000000,
      netProfit: 20000000,
    },
    statistics: {
      totalRegistrations: 1250,
      approvedRegistrations: 1200,
      pendingRegistrations: 35,
      rejectedRegistrations: 15,
      completedSubmissions: 980,
      registrationsByDate: [
        { date: "2024-01-01", count: 45 },
        { date: "2024-01-02", count: 67 },
        { date: "2024-01-03", count: 89 },
        { date: "2024-01-04", count: 123 },
        { date: "2024-01-05", count: 156 },
        { date: "2024-01-06", count: 134 },
        { date: "2024-01-07", count: 98 },
        { date: "2024-01-08", count: 145 },
        { date: "2024-01-09", count: 167 },
        { date: "2024-01-10", count: 178 },
        { date: "2024-01-11", count: 132 },
        { date: "2024-01-12", count: 116 },
      ],
      participantsBySchool: [
        { school: "Đại học Bách Khoa Hà Nội", count: 198 },
        { school: "Đại học Kinh tế Quốc dân", count: 156 },
        { school: "Đại học Công nghệ", count: 134 },
        { school: "Đại học FPT", count: 123 },
        { school: "Đại học Khoa học Tự nhiên", count: 112 },
      ],
      participantsByRegion: [
        { region: "Hà Nội", count: 456 },
        { region: "TP. Hồ Chí Minh", count: 389 },
        { region: "Đà Nẵng", count: 167 },
        { region: "Hải Phòng", count: 123 },
        { region: "Cần Thơ", count: 115 },
      ],
      averageRating: 4.6,
      completionRate: 81.6,
    },
    participants: [
      {
        id: "p1",
        userId: "1",
        user: {
          id: "1",
          fullName: "Nguyễn Văn A",
          username: "nguyenvana",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Bách Khoa Hà Nội",
          email: "nguyenvana@example.com",
        },
        registrationDate: new Date("2024-01-15"),
        status: "approved",
        paymentStatus: "paid",
        submissionStatus: "submitted",
        score: 85,
        rank: 12,
      },
      {
        id: "p2",
        userId: "2",
        user: {
          id: "2",
          fullName: "Trần Thị B",
          username: "tranthib",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Kiến trúc Hà Nội",
          email: "tranthib@example.com",
        },
        registrationDate: new Date("2024-01-14"),
        status: "approved",
        paymentStatus: "paid",
        submissionStatus: "reviewed",
        score: 92,
        rank: 5,
      },
    ],
  },
  {
    id: "2",
    competitionId: "3",
    competition: mockCompetitions[2],
    organizerId: "org1",
    organizer: {
      id: "org1",
      name: "Vietnam Startup Foundation",
      email: "admin@vietnamstartup.vn",
      avatar: "/api/placeholder/150/150",
    },
    status: "completed",
    createdAt: new Date("2023-10-01"),
    updatedAt: new Date("2024-01-15"),
    settings: {
      allowLateRegistration: true,
      autoApproveRegistrations: false,
      maxParticipants: 500,
      registrationFee: 50000,
      emailNotifications: true,
      publicLeaderboard: true,
      allowTeamRegistration: true,
      maxTeamSize: 4,
    },
    finances: {
      budget: 200000000,
      revenue: [
        {
          id: "r4",
          type: "revenue",
          category: "Phí đăng ký",
          description: "Phí đăng ký từ thí sinh",
          amount: 22500000,
          date: new Date("2023-12-15"),
          source: "Registration fees",
          status: "confirmed",
        },
        {
          id: "r5",
          type: "revenue",
          category: "Tài trợ",
          description: "Tài trợ từ Design Agency",
          amount: 80000000,
          date: new Date("2023-11-20"),
          source: "Design Agency Sponsorship",
          status: "confirmed",
        },
      ],
      expenses: [
        {
          id: "e4",
          type: "expense",
          category: "Giải thưởng",
          description: "Tiền thưởng cho các đội chiến thắng",
          amount: 100000000,
          date: new Date("2023-12-20"),
          status: "confirmed",
        },
        {
          id: "e5",
          type: "expense",
          category: "Workshop",
          description: "Chi phí tổ chức workshop",
          amount: 15000000,
          date: new Date("2023-12-01"),
          status: "confirmed",
        },
      ],
      prizePool: 100000000,
      sponsorships: [
        {
          id: "s3",
          sponsor: "Design Agency",
          amount: 80000000,
          type: "cash",
          benefits: ["Logo placement", "Workshop hosting"],
          status: "completed",
          contractDate: new Date("2023-11-20"),
        },
      ],
      totalRevenue: 102500000,
      totalExpenses: 115000000,
      netProfit: -12500000,
    },
    statistics: {
      totalRegistrations: 450,
      approvedRegistrations: 420,
      pendingRegistrations: 0,
      rejectedRegistrations: 30,
      completedSubmissions: 398,
      registrationsByDate: [
        { date: "2023-11-01", count: 25 },
        { date: "2023-11-02", count: 34 },
        { date: "2023-11-03", count: 42 },
        { date: "2023-11-04", count: 38 },
        { date: "2023-11-05", count: 51 },
        { date: "2023-11-06", count: 47 },
        { date: "2023-11-07", count: 39 },
        { date: "2023-11-08", count: 56 },
        { date: "2023-11-09", count: 62 },
        { date: "2023-11-10", count: 56 },
      ],
      participantsBySchool: [
        { school: "Đại học Kiến trúc Hà Nội", count: 89 },
        { school: "Đại học Mỹ thuật", count: 67 },
        { school: "Đại học Bách Khoa Hà Nội", count: 54 },
        { school: "Đại học FPT", count: 78 },
        { school: "Đại học Công nghệ", count: 45 },
      ],
      participantsByRegion: [
        { region: "Hà Nội", count: 178 },
        { region: "TP. Hồ Chí Minh", count: 134 },
        { region: "Đà Nẵng", count: 89 },
        { region: "Hải Phòng", count: 34 },
        { region: "Cần Thơ", count: 15 },
      ],
      averageRating: 4.8,
      completionRate: 94.7,
    },
    participants: [
      {
        id: "p3",
        userId: "2",
        user: {
          id: "2",
          fullName: "Trần Thị B",
          username: "tranthib",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Kiến trúc Hà Nội",
          email: "tranthib@example.com",
        },
        registrationDate: new Date("2023-11-15"),
        status: "approved",
        paymentStatus: "paid",
        submissionStatus: "reviewed",
        score: 96,
        rank: 1,
      },
      {
        id: "p4",
        userId: "6",
        user: {
          id: "6",
          fullName: "Phạm Văn F",
          username: "phamvanf",
          avatar: "/api/placeholder/150/150",
          school: "Đại học FPT",
          email: "phamvanf@example.com",
        },
        registrationDate: new Date("2023-11-10"),
        status: "approved",
        paymentStatus: "paid",
        submissionStatus: "reviewed",
        score: 88,
        rank: 8,
      },
    ],
  },
  {
    id: "3",
    competitionId: "2",
    competition: mockCompetitions[1],
    organizerId: "org2",
    organizer: {
      id: "org2",
      name: "ACM Vietnam",
      email: "admin@acmvn.org",
      avatar: "/api/placeholder/150/150",
    },
    status: "ongoing",
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2024-01-20"),
    settings: {
      allowLateRegistration: false,
      autoApproveRegistrations: false,
      maxParticipants: 1000,
      registrationFee: 0,
      emailNotifications: true,
      publicLeaderboard: true,
      allowTeamRegistration: true,
      maxTeamSize: 3,
    },
    finances: {
      budget: 150000000,
      revenue: [
        {
          id: "r6",
          type: "revenue",
          category: "Tài trợ",
          description: "Tài trợ từ Tech Companies",
          amount: 120000000,
          date: new Date("2024-01-05"),
          source: "Multiple Tech Sponsors",
          status: "confirmed",
        },
      ],
      expenses: [
        {
          id: "e6",
          type: "expense",
          category: "Giải thưởng",
          description: "Medals và certificates",
          amount: 30000000,
          date: new Date("2024-01-15"),
          status: "pending",
        },
        {
          id: "e7",
          type: "expense",
          category: "Tổ chức sự kiện",
          description: "Server costs và judging system",
          amount: 45000000,
          date: new Date("2024-01-10"),
          status: "confirmed",
        },
      ],
      prizePool: 30000000,
      sponsorships: [
        {
          id: "s4",
          sponsor: "Multiple Tech Companies",
          amount: 120000000,
          type: "cash",
          benefits: ["Recruitment", "Brand exposure"],
          status: "confirmed",
          contractDate: new Date("2024-01-05"),
        },
      ],
      totalRevenue: 120000000,
      totalExpenses: 75000000,
      netProfit: 45000000,
    },
    statistics: {
      totalRegistrations: 890,
      approvedRegistrations: 850,
      pendingRegistrations: 25,
      rejectedRegistrations: 15,
      completedSubmissions: 0,
      registrationsByDate: [
        { date: "2024-01-01", count: 78 },
        { date: "2024-01-02", count: 92 },
        { date: "2024-01-03", count: 84 },
        { date: "2024-01-04", count: 96 },
        { date: "2024-01-05", count: 103 },
        { date: "2024-01-06", count: 89 },
        { date: "2024-01-07", count: 76 },
        { date: "2024-01-08", count: 94 },
        { date: "2024-01-09", count: 102 },
        { date: "2024-01-10", count: 98 },
        { date: "2024-01-11", count: 78 },
      ],
      participantsBySchool: [
        { school: "Đại học Bách Khoa Hà Nội", count: 145 },
        { school: "Đại học Công nghệ", count: 123 },
        { school: "Đại học FPT", count: 98 },
        { school: "Đại học Khoa học Tự nhiên", count: 87 },
        { school: "Đại học Sư phạm Kỹ thuật", count: 76 },
      ],
      participantsByRegion: [
        { region: "Hà Nội", count: 334 },
        { region: "TP. Hồ Chí Minh", count: 267 },
        { region: "Đà Nẵng", count: 123 },
        { region: "Hải Phòng", count: 89 },
        { region: "Cần Thơ", count: 77 },
      ],
      averageRating: 4.5,
      completionRate: 0,
    },
    participants: [
      {
        id: "p5",
        userId: "1",
        user: {
          id: "1",
          fullName: "Nguyễn Văn A",
          username: "nguyenvana",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Bách Khoa Hà Nội",
          email: "nguyenvana@example.com",
        },
        registrationDate: new Date("2024-01-08"),
        status: "approved",
        paymentStatus: "paid",
        submissionStatus: "not-submitted",
        score: undefined,
        rank: undefined,
      },
      {
        id: "p6",
        userId: "3",
        user: {
          id: "3",
          fullName: "Lê Văn C",
          username: "levanc",
          avatar: "/api/placeholder/150/150",
          school: "Đại học Công nghệ",
          email: "levanc@example.com",
        },
        registrationDate: new Date("2024-01-05"),
        status: "approved",
        paymentStatus: "paid",
        submissionStatus: "not-submitted",
        score: undefined,
        rank: undefined,
      },
    ],
  },
];
